# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_id', models.PositiveIntegerField()),
                ('country_code', models.CharField(max_length=3)),
                ('state_code', models.CharField(max_length=3)),
                ('conference_id', models.PositiveIntegerField(null=True)),
                ('union_id', models.PositiveIntegerField(null=True)),
                ('division_id', models.PositiveIntegerField(null=True)),
                ('members', models.PositiveSmallIntegerField()),
                ('contact1_id', models.PositiveIntegerField()),
                ('contact2_id', models.PositiveIntegerField(null=True)),
                ('contact3_id', models.PositiveIntegerField(null=True)),
                ('phone', models.CharField(max_length=45, null=True)),
                ('fax', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=45, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('facebook', models.CharField(max_length=255, null=True)),
                ('twitter', models.CharField(max_length=255, null=True)),
                ('language1', models.CharField(max_length=3)),
                ('language2', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('internet_domain', models.CharField(max_length=3)),
                ('phone_prefix', models.PositiveSmallIntegerField()),
                ('language1', models.CharField(max_length=3)),
                ('language2', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('code2', models.CharField(max_length=2, null=True, unique=True)),
                ('english_name', models.CharField(max_length=45)),
                ('french_name', models.CharField(max_length=45)),
                ('spanish_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('state_code', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=45)),
                ('zip_code', models.CharField(max_length=8)),
                ('geox', models.FloatField()),
                ('geoy', models.FloatField()),
                ('church_id', models.PositiveIntegerField()),
                ('person_id', models.PositiveIntegerField()),
                ('event_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=45, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('facebook', models.CharField(max_length=255, null=True)),
                ('twitter', models.CharField(max_length=255, null=True)),
                ('location_id', models.PositiveIntegerField()),
                ('country_code', models.CharField(max_length=3)),
                ('state_code', models.CharField(max_length=3)),
                ('church_id', models.PositiveIntegerField()),
                ('church_role', models.CharField(choices=[('GU', 'Guest'), ('ME', 'Member'), ('PA', 'Pastor'), ('EL', 'Elder'), ('DE', 'Deacon')], default='GU', max_length=2)),
                ('password_hash', models.CharField(max_length=255)),
                ('rights', models.CharField(choices=[('N', 'None'), ('U', 'User'), ('A', 'Admin')], default='U', max_length=1)),
                ('last_login', models.DateTimeField()),
                ('can_login', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=45)),
                ('postal_code', models.CharField(max_length=3)),
                ('language', models.CharField(max_length=3)),
                ('zip_from', models.CharField(max_length=3, null=True)),
                ('zip_to', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
