# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboard', '0003_auto_20170307_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='members',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='internet_domain',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_prefix',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='church_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('WO', 'Worship'), ('SS', 'Sabbath School'), ('SE', 'Sermon'), ('PO', 'Potluck'), ('RE', 'Retreat'), ('CO', 'Conference'), ('OT', 'Other')], default='WO', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='french_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='spanish_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='church_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='event_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='geox',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='geoy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='person_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='church_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='location_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='church_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='postal_code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
