# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eboard', '0007_auto_20170309_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='email_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='newsletter_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sms_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='church',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conference_member', to='eboard.Church'),
        ),
        migrations.AlterField(
            model_name='church',
            name='contact1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact1_church', to='eboard.Person'),
        ),
        migrations.AlterField(
            model_name='church',
            name='contact2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact2_church', to='eboard.Person'),
        ),
        migrations.AlterField(
            model_name='church',
            name='contact3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact3_church', to='eboard.Person'),
        ),
        migrations.AlterField(
            model_name='church',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_member', to='eboard.Church'),
        ),
        migrations.AlterField(
            model_name='church',
            name='language1',
            field=models.ForeignKey(default=b'eng', on_delete=django.db.models.deletion.PROTECT, related_name='church', to='eboard.Language'),
        ),
        migrations.AlterField(
            model_name='church',
            name='language2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='church2', to='eboard.Language'),
        ),
        migrations.AlterField(
            model_name='church',
            name='union',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_member', to='eboard.Church'),
        ),
        migrations.AlterField(
            model_name='country',
            name='language1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country', to='eboard.Language'),
        ),
        migrations.AlterField(
            model_name='country',
            name='language2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country2', to='eboard.Language'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='eboard.Person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='language1',
            field=models.ForeignKey(default=b'eng', on_delete=django.db.models.deletion.PROTECT, related_name='event1', to='eboard.Language'),
        ),
        migrations.AlterField(
            model_name='event',
            name='language2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event2', to='eboard.Language'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer', to='eboard.Person'),
        ),
    ]
